### ISSUE TITLE
Let a single worker listen to multiple queues

### ISSUE THREAD

**Issue by leosussan** [samuelcolvin/arq#186]
Topic. Some context: I have a series of jobs associated with distinct queue names, but my desired implementation differs based on the environment.

For local development & deploys of test versions, I'd like to define a single worker to listen & respond to jobs from multiple queues (as defined by `queue_name`) so as to reduce the overall footprint of a single deployment. This doesn't seem to be possible currently, at least as defined in the documentation, but would be happy to be shown otherwise.

For production deploys, I have distinct workers each tasked to different queues. This is supported by the current structure & it works exceedingly well.

Is this currently possible?

Thank you!

**Comment by leosussan** [comment]
Adding a quick note to this: the syntax I've got in mind

```python
class WorkerSettings:
    ...
    queue_name = ["arq:queue_name_1", "arq:queue_name_2"]
    ...
```

where `queue_name`'s typing becomes `Union[str, List[str]]`

Thoughts on the concept & on where a person would begin if they wanted to take it on?

**Comment by samuelcolvin** [comment]
Sorry for the slow reply.

I see the use case, if this can be achieved without damaging performance, I'd be happy to accept a PR.

---

This should probably be implemented as a separate worker class to avoid damaging performance, adding more complexity or introducing backwards incompatible changes to the main worker class. However some small changes might be required in the main worker class to ease the development of a sub-class.

Because the current worker is not doing a `BLPOP` type operation on the main queue sorted set, it shouldn't be too hard to sub-class it to monitor multiple queues

Perhaps we could implement some kind of round-robin approach to checking queues: instead of polling a single sorted set for jobs, the worker polls each sorted set in tur. This might lead to a slight latency increase in processing jobs, but not too much.

---

Another approach for what you want, would be to leave the current worker class unchanged, and just run multiple workers in the same process and event loop.

This way the only changes needed would be to shutdown behaviour (at least that's the only thing that's occurred to me now). #183 might be helpful here.

---

It's hard to know without digging into this which approach would require the least work, but I probably favour the second.

I don't have time to work on this myself right now, but I'll review a PR if you're able to work on it.

**Comment by leosussan** [comment]
OK - this is great. I'll try to set aside some time to take a stab.

**Comment by art1415926535** [comment]
> Adding a quick note to this: the syntax I've got in mind
> 
> ```python
> class WorkerSettings:
>     ...
>     queue_name = ["arq:queue_name_1", "arq:queue_name_2"]
>     ...
> ```
> 
> where `queue_name`'s typing becomes `Union[str, List[str]]`
> 
> Thoughts on the concept & on where a person would begin if they wanted to take it on?


To me it looks like task priorities.

[e-Book - Redis in Action: Task Priorities](https://redislabs.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-4-task-queues/6-4-1-first-in-first-out-queues/)

**Comment by samuelcolvin** [comment]
arq prior to `v0.16` used a list as the basic data structure and `BLPOP` to get about jobs - as described in the link above.

As described in the docs, I completely rewrote arq to support "pessimistic execution" where jobs aren't removed from the queue until they've finished (either successfully completed or failed). Obviously this doesn't work with `*POP` operations, so what's described in your link doesn't work here.

**Comment by art1415926535** [comment]
I mean, this style can confuse someone.

Running multiple workers in a single event loop seems more clear.

**Comment by samuelcolvin** [comment]
> I mean, this style can confuse someone.
> 
> Running multiple workers in a single event loop seems more clear.

Agreed
