### ISSUE TITLE
Question: Order of jobs

### ISSUE THREAD

**Issue by Minstel** [samuelcolvin/arq#262]
On our system we noticed the following behaviour: when a lot of jobs are created in a short period of time (a few hundred) and they are relatively long-running, jobs that were added last are executed faster then onces that were added first. That made us think that **arq** uses LIFO algorithm. Is this true? And if so, is it possible to make it work as FIFO?

**Comment by Minstel** [comment]
If this is not true, how does **arq** choses jobs for execution. I've read it uses sorted sets. How are jobs sorted in it?

**Comment by Minstel** [comment]
Eventually seems like this is not true, so closing

**Comment by samuelcolvin** [comment]
arq uses a sorted set, jobs are added with a timestamp after which they should be run. See [`_defer_until` and `_defer_by`](https://github.com/samuelcolvin/arq/blob/118308ae21ec5d85b644bcf426d8da9a7d4762d7/arq/connections.py#L116-L117) arguments to `enqueue_job`.

Jobs where that "defer until" time is now or in the past are started, priorities on FIFO bases - e.g. the job with the oldest "defer until" timestamp is run first.

This means:
* you can set up jobs to run in the future by using a "defer until" time some time in the future
* you can make a job high priority by setting the "defer until" time arbitrarily far back in the past, meaning that job will take priority over job already created
* back-off and retrying are relatively easy since you just ask the job to run x seconds in the future

Hope that makes sense.
