### ISSUE TITLE
Redis Cluster

### ISSUE THREAD

**Issue by kamkash** [samuelcolvin/arq#358]
ARQ experts,

Is there a recommended way of initializing/connecting to a Redis Cluster?
Both for the scheduler and the workers?

**Comment by tadejsv** [comment]
What do you mean? Connection to redis is done within `arq` objects, there's nothing you need to do here

**Comment by tadejsv** [comment]
Oh, do you mean this? https://redis-py.readthedocs.io/en/stable/connections.html?highlight=cluster

I guess no way to do it for now, since `ArqRedis` is based on the normal `Redis` client, not `RedisCluster`
https://github.com/samuelcolvin/arq/blob/1495be6c234509df1dfdc0db620388d909c8cdb8/arq/connections.py#L74-L80

**Comment by kamkash** [comment]
> Oh, do you mean this? https://redis-py.readthedocs.io/en/stable/connections.html#rediscluster

Yes. I mean using a async.io rediscluster client to connect to Redis cluster nodes.

It would be like running redis-cli with a -c command.
$ redis-cli -p 7000 -c

With current arq scheduler and workers,  if I run against a Redis cluster I get a MOVED error:
"(error) MOVED 16281 192.168.0.14:6379"

This is a common issue with Redis clusters where the key might not be on the Redis node/shard the client is accessing.

Do you have any suggestions/workaround? Other than submitting a pull request?
I am currently evaluating arq and supporting Redis clusters is a key requirement for me.
I am not sure if I will have the time to add the support to arq.

**Comment by tadejsv** [comment]
Hm, I see. I have never used redis clusters, but just from looking at it, `RedisCluster` seems to be an almost drop-in replacement for `Redis`.

So I would advise you to try like this: fork this project and in `arq/arq/connections.py` just replace all (3) apperances of `Redis` with `RedisCluster` - and install the package locally using

```
pip install -e .
```

Then try if it works.

Unfortunately I can't think of a way to do what you want to do without modifying the source code of `arq`. If you are fine with this solution (and it turns out to work), I think it would be not very difficult to create a PR for this - would just require making the current `ArqRedis` a mixin, and then using it to create `ArqRedis` and `ArqRedisCluster`

**Comment by kamkash** [comment]
thank you @tadejsv.  I will take a look.

**Comment by JonasKs** [comment]
Closing in favor of #385.
