### ISSUE TITLE
"Job already running elsewhere" by just changing logging config

### ISSUE THREAD

**Issue by waldner** [samuelcolvin/arq#375]
Not sure I understand what's going on here. Let me give a sample reproducer:

Here's the worker code (`w.py`):

```
import logging
import httpx
from arq.connections import RedisSettings

logger = logging.root

async def startup(ctx):
    logging.basicConfig(level=logging.DEBUG)

async def myjob(ctx, msg):
    session: httpx.AsyncClient = httpx.AsyncClient()
    response = await session.get('https://www.kernel.org')
    await session.aclose()
    logger.info(f'response: {response}')
    return True

class WorkerSettings:
    redis_settings = RedisSettings(host="my.redis.com")
    functions = [myjob]
    on_startup = startup
```

Here's the submitter code (`main.py` or whatever):

```
import asyncio

from arq import create_pool
from arq.connections import RedisSettings

async def main():
    redis = await create_pool(RedisSettings(host="my.redis.com"))
    for msg in ('foo', 'bar', 'baz'):
        job = await redis.enqueue_job('myjob', msg)

if __name__ == '__main__':
    asyncio.run(main())
```

Now, if I run the worker with 

```
arq  w.WorkerSettings
```

everything is fine and I see the expected messages in the worker log. However, if I run the worker with:

```
arq --custom-log-dict logconf.logconf w.WorkerSettings
```

I get plenty of "job already running elsewhere" messages, eg

```
DEBUG:arq.worker:job 369084a4186246259a3be84676c21af3 already running elsewhere
DEBUG:arq.worker:job f5638ebd9ae74743ae76733b3c49f5f7 already running elsewhere
DEBUG:arq.worker:job 1bdd22c9dfa548edbe5226d081c6a7ec already running elsewhere
DEBUG:arq.worker:job c3586645703b4aab818208a94d679b6c already running elsewhere
DEBUG:arq.worker:job 1e4b3d0f74a7497293ce0b71c07fb023 already running elsewhere
...
```

Here's the contents of `logconf.py`:

```
logconf = {"version": 1, "disable_existing_loggers": False, "loggers": {}}
```

**Comment by JonasKs** [comment]
I haven't tested locally and writing this on my phone so a bit hard to debug properly, but I think I know what's going on here, and this seems like intended behavior. 

First of all, the only difference you're seeing is more logs. This is because you've enabled debug logs - there's nothing wrong going on here. 

The way arq work is explained in my comment here: https://github.com/samuelcolvin/arq/issues/343#issuecomment-1248317777 , but in short, what you're seeing is:

- you queue a job, let's say `my_job_1`
- task is picked, and `arq` adds a key to redis: `arq:in-progress:my_job_1` to mark the job as running. 
- very, very shortly after, it checks again. The `my_job_1` is still running so it won't pick that job again, and `arq` debug logs this (as you see)
- task is done, the keys related to this job are deleted.

**Comment by waldner** [comment]
You're right, and it's my fault. I thought that doing `logging.basicConfig(level=logging.DEBUG)` would also influence arq's logger, which of course it doesn't (my misunderstanding of how python logging works). Now with a proper test I DO see those messages even with the vanilla arq logger config, only tweaked to raise the log level to DEBUG (ie with `--verbose`).

Sorry for the noise.
