### ISSUE TITLE
Examples how to integrate arq

### ISSUE THREAD

**Issue by barrachri** [samuelcolvin/arq#69]
Hi @samuelcolvin, thanks for arq!

I'd like to integrate arq with aiohttp web application to run some long jobs in the background.

Do you have some examples for this?

If I understood right I can create a remote worker specifying the redis server and run it.
Then inside the app I can create an Actor using the same redis server that sends jobs to the worker.

Is it correct?

**Comment by samuelcolvin** [comment]
That's correct, I'll add an examples. Have a look at
https://github.com/tutorcruncher/socket-server which is a good example.

On 26 Aug 2017 12:23 am, "Christian Barra" <notifications@github.com> wrote:

Hi @samuelcolvin <https://github.com/samuelcolvin>, thanks for arq!

I'd like to integrate arq with aiohttp web application to run some long
jobs in the background.

Do you have some examples for this?

If I understood right I can create a remote worker specifying the redis
server and run it.
Then inside the app I can create an Actor using the same redis server the
send jobs to the worker.

Is it correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samuelcolvin/arq/issues/69>, or mute the thread

**Comment by barrachri** [comment]
Thanks :)

**Comment by samuelcolvin** [comment]
I need to add docs.

**Comment by samuelcolvin** [comment]
Done. See https://arq-docs.helpmanual.io/#usage-with-aiohttp and the `/demo` directory.
